In [76]:
import pandas as pd

In [ ]:
df = pd.read_csv('../data/raw/complaints_processed.csv')
df.drop(columns='Unnamed: 0',inplace=True)
df.head(5)

            product                                          narrative
0       credit_card  purchase order day shipping amount receive pro...
1       credit_card  forwarded message date tue subject please inve...
2    retail_banking  forwarded message cc sent friday pdt subject f...
3  credit_reporting  payment history missing credit report speciali...
4  credit_reporting  payment history missing credit report made mis...

In [78]:
df.shape

(162421, 2)

In [79]:
df.isna().sum()

product       0
narrative    10
dtype: int64

In [80]:
df['product'].value_counts()

product
credit_reporting       91179
debt_collection        23150
mortgages_and_loans    18990
credit_card            15566
retail_banking         13536
Name: count, dtype: int64

In [81]:
df['narrative'].iloc[55]

'got turned made impossible work day knowing time received check mail go deposit say loan interest control sometimes get paid last person get paid transaction close additional governing factor make easier company would start calling whenever payment late first day past due date time day asked contact however never honored request communication became literal harassment yet office never available communicate sent account attorney served civil warrant attempted talk attorney office separate occasion asked negotiate amount owed told contact company call company negotiate amount owed even attorney never attempted negotiate amount company never provided term loan writing intentionally make hard pull credit every month intentionally damaging credit told give permission pull credit said right absolutely crazy pay still pull credit like wo negotiate lesser paid full balance everyone negotiates outstanding balance say term provided much damage choose literally company malicious mortgage lender would soft pull damage person credit intentionally trying continued damage even continued make hard pull credit even sent attorney even though say allowed talk seriously someone need review small company people'

In [82]:
df.dropna(inplace=True)

In [83]:
df.shape

(162411, 2)

In [84]:
df.duplicated().sum()

np.int64(37735)

In [85]:
df.drop_duplicates(inplace=True)
df[df['narrative']=='name']

                 product narrative
162415   debt_collection      name
162417       credit_card      name
162420  credit_reporting      name

In [86]:
df = df[df['narrative'].str.len() > 10]
df.shape

(124620, 2)

In [87]:
df.duplicated().sum()

np.int64(0)

In [88]:
df.to_csv('../data/processed/cleaned_complaints.csv', index=False)
print("Clean data saved successfully!")

Clean data saved successfully!